/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OnboardingStartRouteImport } from './routes/onboarding.start'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as OnboardingInviteRouteImport } from './routes/onboarding.invite'
import { Route as OnboardingConnectRouteImport } from './routes/onboarding.connect'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardCollectorsIndexRouteImport } from './routes/dashboard.collectors.index'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard.projects.$id'
import { Route as DashboardCollectorsUploadRouteImport } from './routes/dashboard.collectors.upload'
import { Route as DashboardCollectorsIdRouteImport } from './routes/dashboard.collectors.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingStartRoute = OnboardingStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingInviteRoute = OnboardingInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => OnboardingRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollectorsIndexRoute =
  DashboardCollectorsIndexRouteImport.update({
    id: '/collectors/',
    path: '/collectors/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollectorsUploadRoute =
  DashboardCollectorsUploadRouteImport.update({
    id: '/collectors/upload',
    path: '/collectors/upload',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCollectorsIdRoute = DashboardCollectorsIdRouteImport.update({
  id: '/collectors/$id',
  path: '/collectors/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/start': typeof OnboardingStartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collectors/$id': typeof DashboardCollectorsIdRoute
  '/dashboard/collectors/upload': typeof DashboardCollectorsUploadRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/collectors/': typeof DashboardCollectorsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/start': typeof OnboardingStartRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/collectors/$id': typeof DashboardCollectorsIdRoute
  '/dashboard/collectors/upload': typeof DashboardCollectorsUploadRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/collectors': typeof DashboardCollectorsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/start': typeof OnboardingStartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/collectors/$id': typeof DashboardCollectorsIdRoute
  '/dashboard/collectors/upload': typeof DashboardCollectorsUploadRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/collectors/': typeof DashboardCollectorsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sitemap.xml'
    | '/onboarding/connect'
    | '/onboarding/invite'
    | '/onboarding/profile'
    | '/onboarding/start'
    | '/dashboard/'
    | '/dashboard/collectors/$id'
    | '/dashboard/collectors/upload'
    | '/dashboard/projects/$id'
    | '/dashboard/collectors/'
    | '/dashboard/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sitemap.xml'
    | '/onboarding/connect'
    | '/onboarding/invite'
    | '/onboarding/profile'
    | '/onboarding/start'
    | '/dashboard'
    | '/dashboard/collectors/$id'
    | '/dashboard/collectors/upload'
    | '/dashboard/projects/$id'
    | '/dashboard/collectors'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sitemap.xml'
    | '/onboarding/connect'
    | '/onboarding/invite'
    | '/onboarding/profile'
    | '/onboarding/start'
    | '/dashboard/'
    | '/dashboard/collectors/$id'
    | '/dashboard/collectors/upload'
    | '/dashboard/projects/$id'
    | '/dashboard/collectors/'
    | '/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/onboarding/start': {
      id: '/onboarding/start'
      path: '/start'
      fullPath: '/onboarding/start'
      preLoaderRoute: typeof OnboardingStartRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/invite': {
      id: '/onboarding/invite'
      path: '/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof OnboardingInviteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/connect': {
      id: '/onboarding/connect'
      path: '/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collectors/': {
      id: '/dashboard/collectors/'
      path: '/collectors'
      fullPath: '/dashboard/collectors/'
      preLoaderRoute: typeof DashboardCollectorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collectors/upload': {
      id: '/dashboard/collectors/upload'
      path: '/collectors/upload'
      fullPath: '/dashboard/collectors/upload'
      preLoaderRoute: typeof DashboardCollectorsUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collectors/$id': {
      id: '/dashboard/collectors/$id'
      path: '/collectors/$id'
      fullPath: '/dashboard/collectors/$id'
      preLoaderRoute: typeof DashboardCollectorsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCollectorsIdRoute: typeof DashboardCollectorsIdRoute
  DashboardCollectorsUploadRoute: typeof DashboardCollectorsUploadRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  DashboardCollectorsIndexRoute: typeof DashboardCollectorsIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCollectorsIdRoute: DashboardCollectorsIdRoute,
  DashboardCollectorsUploadRoute: DashboardCollectorsUploadRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  DashboardCollectorsIndexRoute: DashboardCollectorsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  OnboardingInviteRoute: typeof OnboardingInviteRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingStartRoute: typeof OnboardingStartRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingConnectRoute: OnboardingConnectRoute,
  OnboardingInviteRoute: OnboardingInviteRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingStartRoute: OnboardingStartRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
